export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';
export const GET_STUDENT_PERSONAL_INFO = 'GET_STUDENT_PERSONAL_INFO';
export const GET_ALL_EDUCATION = 'GET_ALL_EDUCATION';
export const SHOW_SIGNIN = 'SHOW_SIGNIN';
export const USER_TYPE = 'USER_TYPE';
export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const USER_COMPANY_LOGO = 'USER_COMPANY_LOGO';
export const PROFILE_PHOTO = 'PROFILE_PHOTO';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const LOGIN_DETAILS = 'LOGIN_DETAILS';
export const GET_NAVIGATION_ITEM_SUCCESS = 'GET_NAVIGATION_ITEM_SUCCESS';
export const SAVE_TEMPLATE_ID = "SAVE_TEMPLATE_ID";

