export const GET_APPROVER = 'GET_APPROVER';
export const GET_OTP_FOR_ADD_USER = 'GET_OTP_FOR_ADD_USER';
export const SUPPLIER_ADD_USER = 'SUPPLIER_ADD_USER';
export const All_ADDED_USER = 'All_ADDED_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const AFFECTED_USER = 'AFFECTED_USER';
export const GET_USER_DETAILS = 'GET_PART_DETAILS';
export const CHECK_TOKEN = 'CHECK_TOKEN';
///export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';//
export const SEND_OTP_FOR_UPDATE_PROFILE = 'SEND_OTP_FOR_UPDATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_OTP_FOR_EDIT_USER = 'GET_OTP_FOR_EDIT_USER';
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const GET_COMPANY_TAX_CODE_LIST = 'GET_COMPANY_TAX_CODE_LIST';
export const GET_SUPPLIER_GST_CODE_LIST = 'GET_SUPPLIER_GST_CODE_LIST';
export const GET_COMPANY_WAREHOUSE_ADDRESS_LIST = 'GET_COMPANY_WAREHOUSE_ADDRESS_LIST';
export const GET_COMPANY_ERP_WAREHOUSE_ADDRESS_LIST = 'GET_COMPANY_ERP_WAREHOUSE_ADDRESS_LIST';
export const CLEAR_OTP_FOR_ADD_USER = ' CLEAR_OTP_FOR_ADD_USER';



